{
    "id": "bundle--3717a6be-e2aa-43ec-9764-776bbfc4255b",
    "objects": [
        {
            "created": "2021-03-13T20:11:49.989717Z",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "description": "JetBrains PyCharm before 2019.2 was allocating a buffer of unknown size for one of the connection processes. In a very specific situation, it could lead to a remote invocation of an OOM error message because of Uncontrolled Memory Allocation.",
            "external_references": [
                {
                    "external_id": "CVE-2019-14958",
                    "source_name": "cve"
                }
            ],
            "id": "vulnerability--f96d3133-9e61-47e0-b9b2-adbbb7dbab17",
            "modified": "2021-11-22T14:54:52.900149Z",
            "name": "CVE-2019-14958",
            "spec_version": "2.1",
            "type": "vulnerability"
        }
    ],
    "type": "bundle"
}