{
    "id": "bundle--915756c6-cb5f-40d1-826c-2d903d2ab221",
    "objects": [
        {
            "created": "2021-03-13T20:12:03.73582Z",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "description": "In GraphicsMagick 1.4 snapshot-20190403 Q8, there is a use-after-free in ThrowException and ThrowLoggedException of magick/error.c.",
            "external_references": [
                {
                    "external_id": "CVE-2019-19950",
                    "source_name": "cve"
                }
            ],
            "id": "vulnerability--f5129eaf-bf2a-4e21-a467-ea96575be229",
            "modified": "2021-11-22T14:54:52.900149Z",
            "name": "CVE-2019-19950",
            "spec_version": "2.1",
            "type": "vulnerability"
        }
    ],
    "type": "bundle"
}