{
    "type": "bundle",
    "id": "bundle--5bf3b221-55c3-49eb-9733-4924eadd097f",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--3e1ab73a-b997-46f4-90cc-aacb4482b8fe",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2024-11-21T18:27:43.844356Z",
            "modified": "2024-11-21T18:27:43.844356Z",
            "name": "CVE-2024-53432",
            "description": "While parsing certain malformed PLY files, PCL version 1.14.1 crashes due to an uncaught std::out_of_range exception in PCLPointCloud2::at. This issue could potentially be exploited to cause a denial-of-service (DoS) attack when processing untrusted PLY files.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2024-53432"
                }
            ]
        }
    ]
}